name: Provera cena
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [scrape]

jobs:
  provera:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install curl_cffi beautifulsoup4

      - name: Pokreni skriptu
        env:
          API_URL: https://pratilac-cena-api.vojinovic82.workers.dev
          SCRAPER_SECRET: ${{ secrets.SCRAPER_SECRET }}
        run: |
          python pratilac_cena.py
