name: Provera cena oglasa

on:
  schedule:
    - cron: "0 */2 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  provera:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Pokreni skriptu
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          EMAIL_PRIMALAC: ${{ secrets.EMAIL_PRIMALAC }}
        run: |
          python pratilac_cena.py

      - name: Commituj bazu cena
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add cene_oglasa.json

          git diff --staged --quiet || git commit -m "Ažurirane cene"

          git push
